# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEUojiAaeLj-jQ_2DWmhsX9ZkhuwQfnJ
"""

import numpy as np
import matplotlib.pyplot as plt

# X qiymatlari oralig'ini aniqlaymiz
x = np.linspace(0, 2 * np.pi, 100)

# Sinus funksiyasini hisoblaymiz
y = np.sin(x)

# Grafikni chizamiz
plt.figure(figsize=(8, 6))
plt.plot(x, y, label='sin(x)', color='blue')

# Grafik elementlari
plt.title("Sinus funksiyasi grafigi")
plt.xlabel("x (radian)")
plt.ylabel("sin(x)")
plt.axhline(0, color='black', linewidth=0.8, linestyle='--')
plt.axvline(0, color='black', linewidth=0.8, linestyle='--')
plt.grid(True)
plt.legend()
plt.show()